Lecture03
yamada-0725/RaiseTech pull request #3
Opened 2024-02-22 14:23 UTC by yamada-0725

AWSコース第3回の課題を提出いたします。
ご確認よろしくお願いいたします。

2024-02-22 14:32 UTC, MasatoshiMizumoto requested changes
第2回の報告ファイルが消えるPRになってます！
期待していない動きなら修正お願いします！

2024-02-22 18:35 UTC, yamada-0725 commented
ご確認ありがとうございます。
第２回の報告ファイルは不要と思い削除していました。
報告ファイルをアップロードしたのですが、問題ないでしょうか。

2024-02-23 05:35 UTC, MasatoshiMizumoto commented
このPRをマージすると第2回の中身が空っぽになりますけど良いですか？？

このリポジトリは学習時間、成長の証明として転職活動に使うので、中身がなくなったりファイルの存在自体がなくなるのはNGとさせてください！

2024-02-23 21:08 UTC, yamada-0725 commented
第2回の報告ファイルを削除したコミットを取り消しました。

2024-02-24 06:24 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-02-24 07:45 UTC, merged